/* Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */

final class P2 {
	public static void main(String[] args) {
		final int FOURMIL = 4000000;
		int fib1 = 1, fib2 = 2, sum = 0;

		for(int tfib = fib2; tfib <= FOURMIL;) {
			if(tfib % 2 == 0) sum += tfib;

			tfib = fib1 + fib2;
			fib1 = fib2;
			fib2 = tfib;
		}
		System.out.println(sum);
	}
}
