/* Problem 12
 *
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * The first ten terms would be:
 *
 *                        1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *         1: 1
 *         3: 1,3
 *         6: 1,2,3,6
 *        10: 1,2,5,10
 *        15: 1,3,5,15
 *        21: 1,3,7,21
 *        28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */

final class P12 {
	static int factorsOfNum(int num) {
		int count = 0;
		int lastFactor = 0;
		
		for (int i = 1; i <= num; ++i) {
			if (num % i == 0) {
				if (i * i == num) {
					count = 2 * count - 1;
					break;
				} else if (i * lastFactor == num) {
					count = 2 * count; 
					break;
				} else {
					++count;
					lastFactor = i;
				}
			}
		}

		return count; 	
	}

	public static void main(String[] args) {
		int maxFactors = 0;
		int nTriNum = 0;

		for (int n = 1; maxFactors <= 500; ++n) {
			nTriNum = (n * (n + 1)) / 2;
			int factors = factorsOfNum(nTriNum);

			if (factors > maxFactors) maxFactors = factors;
		}

		System.out.println(nTriNum);
	}
}
